update runners

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,176 +1,155 @@
 name: build
-
 on: [workflow_dispatch, push]
-
 env:
-  PKG_NAME: "http-echo"
-
+    PKG_NAME: "http-echo"
 jobs:
-  get-go-version:
-    name: "Determine Go toolchain version"
-    runs-on: lunar
-    outputs:
-      go-version: ${{ steps.get-go-version.outputs.go-version }}
-    steps:
-      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
-      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
-        with:
-          # This is the minimum required version. Go 1.21+ should pull in new 
-          # toolchains as indicated in go.mod.
-          go-version: '1.21'
-      - name: Determine Go version
-        id: get-go-version
-        # With go1.21+, we can use `go version` to print out the exact toolchain that will be used
-        run: |
-          echo "Building with Go $(go version | awk '{print $3}' | sed -e 's/^go//')"
-          echo "go-version=$(go version | awk '{print $3}' | sed -e 's/^go//')" >> $GITHUB_OUTPUT
-
-  set-product-version:
-    runs-on: lunar
-    outputs:
-      product-version: ${{ steps.set-product-version.outputs.product-version }}
-      product-base-version: ${{ steps.set-product-version.outputs.base-product-version }}
-      product-prerelease-version: ${{ steps.set-product-version.outputs.prerelease-product-version }}
-    steps:
-      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
-      - name: Set Product version
-        id: set-product-version
-        uses: hashicorp/actions-set-product-version@v1
-
-  build-other:
-    needs:
-      - get-go-version
-      - set-product-version
-    runs-on: lunar
-    strategy:
-      fail-fast: true
-      matrix:
-        goos: [windows]
-        goarch: ["amd64"]
-
-    name: Go ${{ needs.get-go-version.outputs.go-version }} ${{ matrix.goos }} ${{ matrix.goarch }} build
-
-    steps:
-      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
-
-      - uses: hashicorp/actions-go-build@main
+    get-go-version:
+        name: "Determine Go toolchain version"
+        runs-on: localdev-nacho-main
+        outputs:
+            go-version: ${{ steps.get-go-version.outputs.go-version }}
+        steps:
+            - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+            - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
+              with:
+                # This is the minimum required version. Go 1.21+ should pull in new 
+                # toolchains as indicated in go.mod.
+                go-version: '1.21'
+            - name: Determine Go version
+              id: get-go-version
+              # With go1.21+, we can use `go version` to print out the exact toolchain that will be used
+              run: |
+                echo "Building with Go $(go version | awk '{print $3}' | sed -e 's/^go//')"
+                echo "go-version=$(go version | awk '{print $3}' | sed -e 's/^go//')" >> $GITHUB_OUTPUT
+    set-product-version:
+        runs-on: localdev-nacho-main
+        outputs:
+            product-version: ${{ steps.set-product-version.outputs.product-version }}
+            product-base-version: ${{ steps.set-product-version.outputs.base-product-version }}
+            product-prerelease-version: ${{ steps.set-product-version.outputs.prerelease-product-version }}
+        steps:
+            - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+            - name: Set Product version
+              id: set-product-version
+              uses: hashicorp/actions-set-product-version@v1
+    build-other:
+        needs:
+            - get-go-version
+            - set-product-version
+        runs-on: localdev-nacho-main
+        strategy:
+            fail-fast: true
+            matrix:
+                goos: [windows]
+                goarch: ["amd64"]
+        name: Go ${{ needs.get-go-version.outputs.go-version }} ${{ matrix.goos }} ${{ matrix.goarch }} build
+        steps:
+            - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+            - uses: hashicorp/actions-go-build@main
+              env:
+                BASE_VERSION: ${{ needs.set-product-version.outputs.product-base-version }}
+                PRERELEASE_VERSION: ${{ needs.set-product-version.outputs.product-prerelease-version}}
+                METADATA_VERSION: ${{ env.METADATA }}
+              with:
+                product_name: ${{ env.PKG_NAME }}
+                product_version: ${{ needs.set-product-version.outputs.product-version }}
+                go_version: ${{ needs.get-go-version.outputs.go-version }}
+                os: ${{ matrix.goos }}
+                arch: ${{ matrix.goarch }}
+                reproducible: report
+                instructions: |
+                    cp LICENSE $TARGET_DIR/LICENSE.txt
+                    make build
+    build-linux:
+        needs:
+            - get-go-version
+            - set-product-version
+        runs-on: localdev-nacho-main
+        strategy:
+            matrix:
+                goos: [linux]
+                goarch: ["amd64"]
+            fail-fast: true
+        name: Go ${{ needs.get-go-version.outputs.go-version }} ${{ matrix.goos }} ${{ matrix.goarch }} build
+        steps:
+            - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+            - uses: hashicorp/actions-go-build@main
+              env:
+                BASE_VERSION: ${{ needs.set-product-version.outputs.product-base-version }}
+                PRERELEASE_VERSION: ${{ needs.set-product-version.outputs.product-prerelease-version}}
+                METADATA_VERSION: ${{ env.METADATA }}
+              with:
+                product_name: ${{ env.PKG_NAME }}
+                product_version: ${{ needs.set-product-version.outputs.product-version }}
+                go_version: ${{ needs.get-go-version.outputs.go-version }}
+                os: ${{ matrix.goos }}
+                arch: ${{ matrix.goarch }}
+                reproducible: report
+                instructions: |
+                    cp LICENSE $TARGET_DIR/LICENSE.txt
+                    make build
+    build-darwin:
+        needs:
+            - get-go-version
+            - set-product-version
+        runs-on: localdev-nacho-main
+        strategy:
+            matrix:
+                goos: [darwin]
+                goarch: ["amd64"]
+            fail-fast: true
+        name: Go ${{ needs.get-go-version.outputs.go-version }} ${{ matrix.goos }} ${{ matrix.goarch }} build
         env:
-          BASE_VERSION: ${{ needs.set-product-version.outputs.product-base-version }}
-          PRERELEASE_VERSION: ${{ needs.set-product-version.outputs.product-prerelease-version}}
-          METADATA_VERSION: ${{ env.METADATA }}
-        with:
-          product_name: ${{ env.PKG_NAME }}
-          product_version: ${{ needs.set-product-version.outputs.product-version }}
-          go_version: ${{ needs.get-go-version.outputs.go-version }}
-          os: ${{ matrix.goos }}
-          arch: ${{ matrix.goarch }}
-          reproducible: report
-          instructions: |
-            cp LICENSE $TARGET_DIR/LICENSE.txt
-            make build
-
-  build-linux:
-    needs:
-      - get-go-version
-      - set-product-version
-    runs-on: lunar
-    strategy:
-      matrix:
-        goos: [linux]
-        goarch: ["amd64"]
-
-      fail-fast: true
-
-    name: Go ${{ needs.get-go-version.outputs.go-version }} ${{ matrix.goos }} ${{ matrix.goarch }} build
-
-    steps:
-      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
-
-      - uses: hashicorp/actions-go-build@main
+            GOOS: ${{ matrix.goos }}
+            GOARCH: ${{ matrix.goarch }}
+        steps:
+            - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+            - uses: hashicorp/actions-go-build@main
+              env:
+                BASE_VERSION: ${{ needs.set-product-version.outputs.product-base-version }}
+                PRERELEASE_VERSION: ${{ needs.set-product-version.outputs.product-prerelease-version}}
+                METADATA_VERSION: ${{ env.METADATA }}
+              with:
+                product_name: ${{ env.PKG_NAME }}
+                product_version: ${{ needs.set-product-version.outputs.product-version }}
+                go_version: ${{ needs.get-go-version.outputs.go-version }}
+                os: ${{ matrix.goos }}
+                arch: ${{ matrix.goarch }}
+                reproducible: report
+                instructions: |
+                    cp LICENSE $TARGET_DIR/LICENSE.txt
+                    make build
+    build-docker-default:
+        name: Docker ${{ matrix.arch }} default release build
+        needs:
+            - set-product-version
+            - build-linux
+        runs-on: localdev-nacho-main
+        strategy:
+            matrix:
+                arch: ["amd64"]
         env:
-          BASE_VERSION: ${{ needs.set-product-version.outputs.product-base-version }}
-          PRERELEASE_VERSION: ${{ needs.set-product-version.outputs.product-prerelease-version}}
-          METADATA_VERSION: ${{ env.METADATA }}
-        with:
-          product_name: ${{ env.PKG_NAME }}
-          product_version: ${{ needs.set-product-version.outputs.product-version }}
-          go_version: ${{ needs.get-go-version.outputs.go-version }}
-          os: ${{ matrix.goos }}
-          arch: ${{ matrix.goarch }}
-          reproducible: report
-          instructions: |
-            cp LICENSE $TARGET_DIR/LICENSE.txt
-            make build
-
-  build-darwin:
-    needs:
-      - get-go-version
-      - set-product-version
-    runs-on: macos-latest
-    strategy:
-      matrix:
-        goos: [darwin]
-        goarch: ["amd64"]
-      fail-fast: true
-
-    name: Go ${{ needs.get-go-version.outputs.go-version }} ${{ matrix.goos }} ${{ matrix.goarch }} build
-
-    env:
-      GOOS: ${{ matrix.goos }}
-      GOARCH: ${{ matrix.goarch }}
-
-    steps:
-      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
-
-      - uses: hashicorp/actions-go-build@main
-        env:
-          BASE_VERSION: ${{ needs.set-product-version.outputs.product-base-version }}
-          PRERELEASE_VERSION: ${{ needs.set-product-version.outputs.product-prerelease-version}}
-          METADATA_VERSION: ${{ env.METADATA }}
-        with:
-          product_name: ${{ env.PKG_NAME }}
-          product_version: ${{ needs.set-product-version.outputs.product-version }}
-          go_version: ${{ needs.get-go-version.outputs.go-version }}
-          os: ${{ matrix.goos }}
-          arch: ${{ matrix.goarch }}
-          reproducible: report
-          instructions: |
-            cp LICENSE $TARGET_DIR/LICENSE.txt
-            make build
-
-  build-docker-default:
-    name: Docker ${{ matrix.arch }} default release build
-    needs:
-      - set-product-version
-      - build-linux
-    runs-on: lunar
-    strategy:
-      matrix:
-        arch: ["amd64"]
-    env:
-      repo: ${{ github.event.repository.name }}
-      version: ${{ needs.set-product-version.outputs.product-version }}
-
-    steps:
-      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
-      - name: Docker Build (Action)
-        uses: hashicorp/actions-docker-build@main
-        with:
-          smoke_test: |
-            TEST_VERSION="$(docker run "${IMAGE_NAME}" -version | awk '/http-echo/{print $2}' | sed s/v//)"
-            if [ "${TEST_VERSION}" != "${version}" ]; then
-              echo "Test FAILED"
-              echo "Test Version: ${TEST_VERSION}"
-              echo "Version: ${version}"
-              exit 1
-            fi
-            echo "Test PASSED"
-          version: ${{ env.version }}
-          target: default
-          arch: ${{ matrix.arch }}
-          tags: |
-            docker.io/hashicorp/${{env.repo}}:${{env.version}}
-          dev_tags: |
-            docker.io/hashicorppreview/${{ env.repo }}:${{ env.version }}-dev
-            docker.io/hashicorppreview/${{ env.repo }}:${{ env.version }}-${{ github.sha }}
-
+            repo: ${{ github.event.repository.name }}
+            version: ${{ needs.set-product-version.outputs.product-version }}
+        steps:
+            - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+            - name: Docker Build (Action)
+              uses: hashicorp/actions-docker-build@main
+              with:
+                smoke_test: |
+                    TEST_VERSION="$(docker run "${IMAGE_NAME}" -version | awk '/http-echo/{print $2}' | sed s/v//)"
+                    if [ "${TEST_VERSION}" != "${version}" ]; then
+                      echo "Test FAILED"
+                      echo "Test Version: ${TEST_VERSION}"
+                      echo "Version: ${version}"
+                      exit 1
+                    fi
+                    echo "Test PASSED"
+                version: ${{ env.version }}
+                target: default
+                arch: ${{ matrix.arch }}
+                tags: |
+                    docker.io/hashicorp/${{env.repo}}:${{env.version}}
+                dev_tags: |
+                    docker.io/hashicorppreview/${{ env.repo }}:${{ env.version }}-dev
+                    docker.io/hashicorppreview/${{ env.repo }}:${{ env.version }}-${{ github.sha }}
